{{ if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qalita-worker
  labels:
    app: "{{ .Release.Name }}-worker"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-worker"
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-worker"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: cli
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          command: ["/bin/sh", "-c"]
          args: ["cat /etc/config/init.sh | /bin/sh; sleep infinity"]
          env:
          - name: QALITA_WORKER_NAME
            value: {{ .Values.worker.name }}
          - name: QALITA_WORKER_MODE
            value: {{ .Values.worker.mode }}
          - name: QALITA_WORKER_ENDPOINT
            value: "http://{{ .Release.Name }}-backend-service:3080"
          - name: QALITA_WORKER_TOKEN
            value: {{ .Values.worker.token }}
{{- if .Values.worker.deployment.extraEnv }}
{{ toYaml .Values.worker.deployment.extraEnv | indent 10 }}
{{- end }}
          volumeMounts:
            - name: init-script
              mountPath: /etc/config
{{- if .Values.worker.pvc.enabled }}
            - name: worker-store-pvc
              mountPath: /data
            - name: worker-store-pvc
              mountPath: /root/.qalita/
              subPath: ./qalita
{{- end }}
{{- if .Values.worker.privileged }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
{{- end }}
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          command: ["/bin/sh", "-c"]
          args: ["cat /etc/config/init.sh | /bin/sh; qalita worker run"]
          env:
          - name: QALITA_WORKER_NAME
            value: {{ .Values.worker.name }}
          - name: QALITA_WORKER_MODE
            value: {{ .Values.worker.mode }}
          - name: QALITA_WORKER_ENDPOINT
            value: "http://{{ .Release.Name }}-backend-service:3080"
          - name: QALITA_WORKER_TOKEN
            value: {{ .Values.worker.token }}
{{- if .Values.worker.deployment.extraEnv }}
{{ toYaml .Values.worker.deployment.extraEnv | indent 10 }}
{{- end }}
          volumeMounts:
            - name: init-script
              mountPath: /etc/config
{{- if .Values.worker.pvc.enabled }}
            - name: worker-store-pvc
              mountPath: /data
            - name: worker-store-pvc
              mountPath: /root/.qalita/
              subPath: ./qalita
{{- end }}
      volumes:
        - name: init-script
          configMap:
            name: "qalita-worker-initscript"
{{- if .Values.worker.pvc.enabled }}
        - name: worker-store-pvc
          persistentVolumeClaim:
            claimName: qalita-worker-store
{{- end }}
{{- if .Values.worker.privileged }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
{{- end }}
      {{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
      - name: qalita-platform-dockerregistry
      {{- end }}
{{ end }}
