{{- if .Values.worker.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qalita-worker-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.worker.pvc.storageSize }}
{{- end }}
